# Generated by Django 3.2.5 on 2022-04-28 13:55

import IceAndSpice
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='feedback_date',
            field=models.DateTimeField(default=IceAndSpice.get_datetime),
        ),
    ]
