# Generated by Django 3.2.5 on 2022-05-07 11:40

import IceAndSpice
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_feedback_feedback_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('expiry_date', models.DateTimeField(default=IceAndSpice.get_datetime)),
                ('discount_percent', models.PositiveIntegerField(default=0)),
                ('title', models.TextField(default='')),
                ('desc', models.TextField(default='')),
                ('coupon_code', models.TextField(default='', primary_key=True, serialize=False)),
            ],
        ),
    ]
