# Generated by Django 3.2.5 on 2022-05-07 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_offers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Offers',
            new_name='Offer',
        ),
    ]
