# Generated by Django 3.2.5 on 2022-05-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_rename_offers_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='coupon_code',
            field=models.CharField(default='', max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='offer',
            name='title',
            field=models.CharField(default='', max_length=20),
        ),
    ]
