# Generated by Django 3.2.5 on 2022-05-09 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '__first__'),
        ('administrator', '0008_alter_offer_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='items',
            field=models.ManyToManyField(blank=True, to='Menu.Menu'),
        ),
    ]
