# Generated by Django 3.2.5 on 2022-05-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0009_offer_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
