# Generated by Django 3.2.5 on 2022-05-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0013_alter_offer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(default='media/offers/default.jpg', upload_to='offers/'),
        ),
    ]
