# Generated by Django 6.0.7 on 2026-07-25 14:33

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0018_alter_offer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=cloudinary.models.CloudinaryField(default='sample/cld-sample-4.jpg', max_length=255, verbose_name='image'),
        ),
    ]
