# Generated by Django 6.0.7 on 2026-07-25 06:38

import Menu
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.CharField(default=Menu.generate_menu_id, editable=False, max_length=6, primary_key=True, serialize=False)),
                ('item_name', models.CharField(default='', max_length=20)),
                ('item_desc', models.CharField(default='', max_length=50)),
                ('category', models.CharField(choices=[('Main', 'Main'), ('Drinks', 'Drinks'), ('Desserts', 'Desserts')], default='Main', max_length=10)),
                ('status', models.CharField(choices=[('IN', 'In Stock'), ('OUT', 'Out of Stock')], default='IN', max_length=3)),
                ('price', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
            ],
        ),
    ]
