# Generated by Django 6.0.7 on 2026-07-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='item_desc',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='menu',
            name='item_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
