# Generated by Django 3.2.5 on 2022-03-12 18:25

import Menu.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0003_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Menu.models.calc_t, max_digits=7),
        ),
    ]
