# Generated by Django 3.2.5 on 2022-02-28 08:21

import Reservation
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.CharField(default=Reservation.generate_reservation_id, editable=False, max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=10)),
                ('date_booked', models.DateTimeField(default=datetime.datetime(2022, 2, 28, 13, 51, 16, 515157))),
                ('date_of_reservation', models.DateTimeField(default=datetime.datetime(2022, 2, 28, 13, 51, 16, 515157))),
                ('persons', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
