# Generated by Django 3.2.5 on 2022-03-12 08:16

import IceAndSpice
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date_booked',
            field=models.DateTimeField(default=IceAndSpice.get_datetime),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_of_reservation',
            field=models.DateTimeField(default=IceAndSpice.get_datetime),
        ),
    ]
