# Generated by Django 3.2.5 on 2022-04-14 09:52

import IceAndSpice
import Order
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Menu', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(default=Order.generate_order_id, editable=False, max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=20)),
                ('address', models.CharField(default='', max_length=200)),
                ('contact', models.CharField(default='', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('order_date', models.DateTimeField(default=IceAndSpice.get_datetime)),
                ('items', models.ManyToManyField(to='Menu.Menu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
