# Generated by Django 3.2.5 on 2022-04-15 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '__first__'),
        ('Order', '0002_order_delivered'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menu.menu')),
            ],
        ),
    ]
