# Generated by Django 3.2.5 on 2022-04-15 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='Order.OrderItem'),
        ),
    ]
