# Generated by Django 3.2.5 on 2022-04-16 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0004_alter_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivered',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('D', 'Delivered'), ('N', 'Not Yet Delivered'), ('C', 'Cancelled')], default='N', max_length=1),
        ),
    ]
