# Generated by Django 3.2.5 on 2022-04-28 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0005_auto_20220416_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('D', 'Delivered'), ('N', 'Confirmed, Not Yet Delivered'), ('C', 'Cancelled'), ('P', 'Pending')], default='P', max_length=1),
        ),
    ]
